name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script:  | 
            cd /root/apps
            if [ ! -d "hawtin-blog" ]; then
              git clone --depth=1 https://github.com/HawtinZeng/hawtin-blog
              cd hawtin-blog
            else
              cd hawtin-blog
              git fetch origin
              git reset --hard origin/main
            fi
              npm install -f --loglevel=error
            npm run build
            rm  /root/apps/blog/* -rf
            cp ./dist/ /home/ubuntu/apps/blog/ -r
            cp ./default.conf /home/ubuntu/apps/blog/
            docker run -d -v /home/ubuntu/apps/blog/dist:/usr/share/nginx/html -v /home/ubuntu/apps/blog/nginxConfd:/etc/nginx/conf.d -p 80:80 nginx:latest
