name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script:  | 
            cd /root/apps
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh 
            if [ ! -d "hawtin-blog" ]; then
              git clone --depth=1 https://github.com/HawtinZeng/hawtin-blog
              cd hawtin-blog
            else
              cd hawtin-blog
              git fetch origin
              git reset --hard origin/main
            fi
              npm install -f --loglevel=error
            npm run build
            docker rm hawtin-blog -f
            docker run -d -v /root/apps/hawtin-blog/dist:/usr/share/nginx/html -v /root/apps/hawtin-blog/nginxConfd:/etc/nginx/conf.d --name hawtin-blog --network=host nginx:latest
